export const AccountActions = {
  SET_LOADING: "ACCOUNT_SET_LOADING",
  SET_USER_DATA: "ACCOUNT_SET_USER_DATA",
  SET_ERROR: "ACCOUNT_SET_ERROR",
};

export const MessageActions = {
  SET_MESSAGE: "MESSAGE_SET",
  SET_VISIBILITY: "MESSAGE_VISIBILITY",
};
